# VIRAT class definitions
VIRAT_CLASS_BACKGROUND = 0
VIRAT_CLASS_PERSON = 1
VIRAT_CLASS_CAR = 2
VIRAT_CLASS_VEHICLE = 3
VIRAT_CLASS_OBJECT = 4
VIRAT_CLASS_BIKE = 5

PERSON_CLASSES = {VIRAT_CLASS_PERSON}
VEHICLE_CLASSES = {VIRAT_CLASS_CAR, VIRAT_CLASS_VEHICLE}
BIKE_CLASSES = {VIRAT_CLASS_BIKE}
OBJECT_CLASSES = {VIRAT_CLASS_OBJECT}
BACKGROUND_CLASSES = {VIRAT_CLASS_BACKGROUND}

VIRAT_CLASS_LABELS = {
    VIRAT_CLASS_BACKGROUND: "背景",
    VIRAT_CLASS_PERSON: "人",
    VIRAT_CLASS_CAR: "小汽车",
    VIRAT_CLASS_VEHICLE: "其他车辆",
    VIRAT_CLASS_OBJECT: "物体",
    VIRAT_CLASS_BIKE: "自行车/摩托车",
}
